Revert "fix `s6wrap --quiet`"
This reverts commit b69c651cba41cfc2035092df24abe891e778ad96.

For smoother merge of following commit that fixes the same issue and
does other stuff

diff --git a/rootfs/etc/services.d/mlat-client/run b/rootfs/etc/services.d/mlat-client/run
--- a/rootfs/etc/services.d/mlat-client/run
+++ b/rootfs/etc/services.d/mlat-client/run
@@ -18,9 +18,9 @@
 #---------------------------------------------------------------------------------------------
 
 APPNAME="mlat-client"
+alias s6wrap='s6wrap --quiet'
 
-
-s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "Started as an s6 service"
+s6wrap --prepend="${APPNAME}" --timestamps --args echo "Started as an s6 service"
 
 source /scripts/common
 source /scripts/interpret_ultrafeeder_config
@@ -32,27 +32,27 @@ declare -A pid_array
 
 if [[ -z "${MLAT_CONFIG}" ]]
 then
-    s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "Warning: MLAT_CONFIG not defined - MLAT will be disabled."
+    s6wrap --prepend="${APPNAME}" --timestamps --args echo "Warning: MLAT_CONFIG not defined - MLAT will be disabled."
     sleep infinity
 fi
 
 if [[ -z "${MLAT_USER}" ]] && [[ -z "${UUID}" ]]
 then
-    s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "ERROR: either UUID or MLAT_USER must be defined - MLAT will be disabled."
+    s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR: either UUID or MLAT_USER must be defined - MLAT will be disabled."
     sleep infinity
 fi
 
 if [[ -z "$LAT$READSB_LAT" ]]; then
-    s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "ERROR: READSB_LAT or LAT must be defined - MLAT will be disabled."
+    s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR: READSB_LAT or LAT must be defined - MLAT will be disabled."
     sleep infinity
 fi
 
 if [[ -z "$LONG$READSB_LON" ]]; then
-    s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "ERROR: READSB_LON or LONG must be defined - MLAT will be disabled."
+    s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR: READSB_LON or LONG must be defined - MLAT will be disabled."
     sleep infinity
 fi
 if [[ -z "$ALT$READSB_ALT" ]]; then
-    s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "ERROR: READSB_ALT or ALT must be defined - MLAT will be disabled."
+    s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR: READSB_ALT or ALT must be defined - MLAT will be disabled."
     sleep infinity
 fi
 
@@ -79,7 +79,7 @@ do
     # Check if the params array has values for the mandatory elements:
     if [[ -z "${params[0]}" ]] || [[ -z "${params[1]}" ]]
     then
-        s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "ERROR -- MLAT_CONFIG is malformed: \"${instance}\". Stopping MLAT execution."
+        s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR -- MLAT_CONFIG is malformed: \"${instance}\". Stopping MLAT execution."
          # shellcheck disable=SC2046
         kill $(ps -s $$ -o pid=)   
         sleep infinity
@@ -134,7 +134,7 @@ do
         MLAT_PARAM+=(--user "${MLAT_USER}")
     else 
         rnd="${RANDOM}"
-        s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "WARNING: MLAT_USER is not set - using random number \"${rnd}\" as MLAT_USER"
+        s6wrap --prepend="${APPNAME}" --timestamps --args echo "WARNING: MLAT_USER is not set - using random number \"${rnd}\" as MLAT_USER"
         MLAT_PARAM+=(--user "${rnd}")
     fi
 
@@ -172,7 +172,7 @@ do
         # generate a random UUID
         UUID="$(cat /proc/sys/kernel/random/uuid)"
         [[ -z "${UUID}" ]] && UUID="$(printf '00000000-ffff-aaaa-%04x-%012x\n' "$RANDOM" "$(date +%s)")"
-        s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "WARNING: UUID is not defined - using randomized uuid \"${UUID}\""
+        s6wrap --prepend="${APPNAME}" --timestamps --args echo "WARNING: UUID is not defined - using randomized uuid \"${UUID}\""
         MLAT_PARAM+=("--uuid ${UUID}")
     fi
 
@@ -187,7 +187,7 @@ do
     # ------------------------------------------------
     # Ready to launch, but wait until readsb is established...
     if ! pgrep readsb >/dev/null; then
-        s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "Delaying start of MLAT client(s) until container is established..."
+        s6wrap --prepend="${APPNAME}" --timestamps --args echo "Delaying start of MLAT client(s) until container is established..."
         while ! pgrep readsb >/dev/null
         do
             sleep 2
@@ -196,13 +196,13 @@ do
     sleep 10     # sleep a bit so everything is well established - starting readsb may take a bit
 
     # run this Mlat_client instance in the background:
-    s6wrap --quiet --prepend="${APPNAME}" --timestamps --args echo "starting: ${MLAT_CMD} ${MLAT_PARAM[*]}"
+    s6wrap --prepend="${APPNAME}" --timestamps --args echo "starting: ${MLAT_CMD} ${MLAT_PARAM[*]}"
 
     #shellcheck disable=SC2069,SC2086
     if [[ -z "${LOGLEVEL}" ]] || [[ "${LOGLEVEL,,}" == "verbose" ]]; then
-        { exec s6wrap --quiet --prepend="${APPNAME}][${params[0]}" --timestamps --args ${execstring}; } &
+        { exec s6wrap --prepend="${APPNAME}][${params[0]}" --timestamps --args ${execstring}; } &
     elif [[ "${LOGLEVEL,,}" == "error" ]]; then
-        { exec s6wrap --quiet --prepend="${APPNAME}][${params[0]}" --timestamps --args ${execstring} 2>&1 >/dev/null; } &
+        { exec s6wrap --prepend="${APPNAME}][${params[0]}" --timestamps --args ${execstring} 2>&1 >/dev/null; } &
     elif [[ "${LOGLEVEL,,}" == "none" ]]; then
        { exec ${execstring} >/dev/null 2>/dev/null; } &
     fi
@@ -230,15 +230,15 @@ do
             servername="$(awk '{print $4}' <<< "${pid_array[$mlat_pid]}")"
             servername="${servername%%:*}"
 
-            [[ "${LOGLEVEL,,}" != "none" ]] && s6wrap --quiet --prepend="${APPNAME}[${servername}" --timestamps --args echo "MLAT_Client ${servername} exited. Attempting to restart." || true
+            [[ "${LOGLEVEL,,}" != "none" ]] && s6wrap --prepend="${APPNAME}[${servername}" --timestamps --args echo "MLAT_Client ${servername} exited. Attempting to restart." || true
             # shellcheck disable=SC2086
             execstring="$(echo ${MLAT_CMD} ${pid_array[$mlat_pid]} | xargs)"
 
             #shellcheck disable=SC2069,SC2086
             if [[ -z "${LOGLEVEL}" ]] || [[ "${LOGLEVEL,,}" == "verbose" ]]; then
-                { exec s6wrap --quiet --prepend="${APPNAME}][${servername}" --timestamps --args ${execstring} 2>&1; } &
+                { exec s6wrap --prepend="${APPNAME}][${servername}" --timestamps --args ${execstring} 2>&1; } &
             elif [[ "${LOGLEVEL,,}" == "error" ]]; then
-                { exec s6wrap --quiet --prepend="${APPNAME}][${servername}" --timestamps --args ${execstring} 2>&1 >/dev/null; } &
+                { exec s6wrap --prepend="${APPNAME}][${servername}" --timestamps --args ${execstring} 2>&1 >/dev/null; } &
             elif [[ "${LOGLEVEL,,}" == "none" ]]; then
                 { exec ${execstring} >/dev/null 2>/dev/null; } &
             fi
