add common script functions

diff --git a/rootfs/etc/services.d/mlat-client/run b/rootfs/etc/services.d/mlat-client/run
--- a/rootfs/etc/services.d/mlat-client/run
+++ b/rootfs/etc/services.d/mlat-client/run
@@ -1,6 +1,7 @@
 #!/usr/bin/with-contenv bash
-# shellcheck shell=bash disable=SC2015,SC2016
+# shellcheck shell=bash disable=SC1091,SC2015,SC2016
 
+source /scripts/common
 
 #---------------------------------------------------------------------------------------------
 # Copyright (C) 2023, Ramon F. Kolb (kx1t)
@@ -35,6 +36,20 @@ fi
 if [[ -z "${MLAT_USER}" ]] && [[ -z "${UUID}" ]]
 then
     echo "[$(date)][${APPNAME}] ERROR: either UUID or MLAT_USER must be defined - MLAT will be disabled."
+    sleep infinity
+fi
+
+if [[ -z "$LAT$READSB_LAT" ]]; then
+    echo "[$(date)][${APPNAME}] ERROR: READSB_LAT or LAT must be defined - MLAT will be disabled."
+    sleep infinity
+fi
+
+if [[ -z "$LONG$READSB_LON" ]]; then
+    echo "[$(date)][${APPNAME}] ERROR: READSB_LON or LONG must be defined - MLAT will be disabled."
+    sleep infinity
+fi
+if [[ -z "$ALT$READSB_ALT" ]]; then
+    echo "[$(date)][${APPNAME}] ERROR: READSB_ALT or ALT must be defined - MLAT will be disabled."
     sleep infinity
 fi
 
@@ -125,7 +140,7 @@ do
         then
             # it exited - let's restart:
             sleep "${RESTARTTIMER}"
-            [[ "$LOGLEVEL,," != "none" ]] && echo  "[$(date)][${APPNAME}] MLAT_Client $(awk '{print $6}' <<< "${pid_array[$mlat_pid]}") exited. Attempting to restart." || true
+            [[ "${LOGLEVEL,,}" != "none" ]] && echo  "[$(date)][${APPNAME}] MLAT_Client $(awk '{print $6}' <<< "${pid_array[$mlat_pid]}") exited. Attempting to restart." || true
             # shellcheck disable=SC2086
             execstring="$(echo ${MLAT_CMD} ${pid_array[$mlat_pid]} | xargs)"
 
