improve s6wrap usage, make sure service stop is respected
alias can only be used in interactive shell scripts, replace with bash array var

diff --git a/rootfs/etc/services.d/mlat-client/run b/rootfs/etc/services.d/mlat-client/run
--- a/rootfs/etc/services.d/mlat-client/run
+++ b/rootfs/etc/services.d/mlat-client/run
@@ -17,10 +17,12 @@
 # If not, see <https://www.gnu.org/licenses/>.
 #---------------------------------------------------------------------------------------------
 
-APPNAME="mlat-client"
-alias s6wrap='s6wrap --quiet'
+trap "pkill -P $$ || true; s6wrap --quiet --timestamps --prepend=mlat-client --args echo 'service stopping'; exit 0" SIGTERM SIGINT SIGHUP SIGQUIT
 
-s6wrap --prepend="${APPNAME}" --timestamps --args echo "Started as an s6 service"
+APPNAME="mlat-client"
+s6wrap=(s6wrap --quiet --timestamps --prepend="${APPNAME}")
+
+"${s6wrap[@]}" --args echo "Started as an s6 service"
 
 source /scripts/common
 source /scripts/interpret_ultrafeeder_config
@@ -32,28 +34,28 @@ declare -A pid_array
 
 if [[ -z "${MLAT_CONFIG}" ]]
 then
-    s6wrap --prepend="${APPNAME}" --timestamps --args echo "Warning: MLAT_CONFIG not defined - MLAT will be disabled."
-    sleep infinity
+    "${s6wrap[@]}" --args echo "Warning: MLAT_CONFIG not defined - MLAT will be disabled."
+    exec sleep infinity
 fi
 
 if [[ -z "${MLAT_USER}" ]] && [[ -z "${UUID}" ]]
 then
-    s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR: either UUID or MLAT_USER must be defined - MLAT will be disabled."
-    sleep infinity
+    "${s6wrap[@]}" --args echo "ERROR: either UUID or MLAT_USER must be defined - MLAT will be disabled."
+    exec sleep infinity
 fi
 
 if [[ -z "$LAT$READSB_LAT" ]]; then
-    s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR: READSB_LAT or LAT must be defined - MLAT will be disabled."
-    sleep infinity
+    "${s6wrap[@]}" --args echo "ERROR: READSB_LAT or LAT must be defined - MLAT will be disabled."
+    exec sleep infinity
 fi
 
 if [[ -z "$LONG$READSB_LON" ]]; then
-    s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR: READSB_LON or LONG must be defined - MLAT will be disabled."
-    sleep infinity
+    "${s6wrap[@]}" --args echo "ERROR: READSB_LON or LONG must be defined - MLAT will be disabled."
+    exec sleep infinity
 fi
 if [[ -z "$ALT$READSB_ALT" ]]; then
-    s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR: READSB_ALT or ALT must be defined - MLAT will be disabled."
-    sleep infinity
+    "${s6wrap[@]}" --args echo "ERROR: READSB_ALT or ALT must be defined - MLAT will be disabled."
+    exec sleep infinity
 fi
 
 # MLAT_CONFIG has the following format:
@@ -69,6 +71,21 @@ MLAT_CONFIG="${MLAT_CONFIG#"${MLAT_CONFIG%%[![:space:]]*}"}"   # strip leading s
 MLAT_CONFIG="${MLAT_CONFIG//; /;}"
 readarray -td ";" mlat_configs < <(printf '%s' "${MLAT_CONFIG}")
 
+
+# wait until readsb is established...
+if ! pgrep readsb >/dev/null; then
+    if [[ -z "${LOGLEVEL}" ]] || [[ "${LOGLEVEL,,}" == "verbose" ]]; then
+        "${s6wrap[@]}" --args echo "Delaying start of MLAT client(s) until container is established..."
+    fi
+    while ! pgrep readsb >/dev/null
+        do
+        sleep 2 &; wait $!
+    done
+    # wait 2 seconds after readsb process exists
+    sleep 2 &; wait $!
+fi
+
+
 # Now loop through the MLAT_CONFIG items and start up an Mlat_client for each of them:
 for instance in "${mlat_configs[@]}"
 do
@@ -79,10 +96,10 @@ do
     # Check if the params array has values for the mandatory elements:
     if [[ -z "${params[0]}" ]] || [[ -z "${params[1]}" ]]
     then
-        s6wrap --prepend="${APPNAME}" --timestamps --args echo "ERROR -- MLAT_CONFIG is malformed: \"${instance}\". Stopping MLAT execution."
+        "${s6wrap[@]}" --args echo "ERROR -- MLAT_CONFIG is malformed: \"${instance}\". Stopping MLAT execution."
          # shellcheck disable=SC2046
         kill $(ps -s $$ -o pid=)   
-        sleep infinity
+        exec sleep infinity
     fi
 
     # Now process the the arguments
@@ -92,7 +109,7 @@ do
     # If the argument isn't any of the above, then it's an "extra argument"
 
     unset uuid_arg lat_arg lon_arg alt_arg input_connect_arg return_port_arg extra_args
-    
+
     for ((i=2; i<${#params[*]}; i++))
     do
         if [[ -n "${params[i]}" ]] && [[ "${params[i]}" =~ ^[0-9]+$ ]]; then
@@ -124,6 +141,8 @@ do
     MLAT_PARAM=(--input-type "${MLAT_INPUT_TYPE:-auto}")
     MLAT_PARAM+=(--server "${params[0]}:${params[1]}")
 
+    servername=${params[0]}
+
     # add return port:
     [ -n "${return_port_arg}" ] && MLAT_PARAM+=("--results beast,listen,${return_port_arg}") || true
 
@@ -134,7 +153,7 @@ do
         MLAT_PARAM+=(--user "${MLAT_USER}")
     else 
         rnd="${RANDOM}"
-        s6wrap --prepend="${APPNAME}" --timestamps --args echo "WARNING: MLAT_USER is not set - using random number \"${rnd}\" as MLAT_USER"
+        "${s6wrap[@]}" --args echo "WARNING: MLAT_USER is not set - using random number \"${rnd}\" as MLAT_USER"
         MLAT_PARAM+=(--user "${rnd}")
     fi
 
@@ -169,11 +188,7 @@ do
     elif [ -n "${UUID}" ]; then
         MLAT_PARAM+=("--uuid ${UUID}")
     else
-        # generate a random UUID
-        UUID="$(cat /proc/sys/kernel/random/uuid)"
-        [[ -z "${UUID}" ]] && UUID="$(printf '00000000-ffff-aaaa-%04x-%012x\n' "$RANDOM" "$(date +%s)")"
-        s6wrap --prepend="${APPNAME}" --timestamps --args echo "WARNING: UUID is not defined - using randomized uuid \"${UUID}\""
-        MLAT_PARAM+=("--uuid ${UUID}")
+        "${s6wrap[@]}" --args echo "WARNING: UUID is not defined, proceeding without UUID"
     fi
 
     # Now add the extra_args, if any:
@@ -184,27 +199,20 @@ do
     # shellcheck disable=SC2048,SC2086
     execstring="$(echo ${MLAT_CMD} ${MLAT_PARAM[*]} | xargs)"
 
+
+    # stagger by 1 second so they don't all start at the same time
+    sleep 1 &; wait $!
+
     # ------------------------------------------------
-    # Ready to launch, but wait until readsb is established...
-    if ! pgrep readsb >/dev/null; then
-        s6wrap --prepend="${APPNAME}" --timestamps --args echo "Delaying start of MLAT client(s) until container is established..."
-        while ! pgrep readsb >/dev/null
-        do
-            sleep 2
-        done
-    fi
-    sleep 10     # sleep a bit so everything is well established - starting readsb may take a bit
-
     # run this Mlat_client instance in the background:
-    s6wrap --prepend="${APPNAME}" --timestamps --args echo "starting: ${MLAT_CMD} ${MLAT_PARAM[*]}"
-
     #shellcheck disable=SC2069,SC2086
     if [[ -z "${LOGLEVEL}" ]] || [[ "${LOGLEVEL,,}" == "verbose" ]]; then
-        { exec s6wrap --prepend="${APPNAME}][${params[0]}" --timestamps --args ${execstring}; } &
+        "${s6wrap[@]}" --prepend="${APPNAME}][${servername}" --args echo "starting: ${MLAT_CMD} ${MLAT_PARAM[*]}"
+        "${s6wrap[@]}" --prepend="${APPNAME}][${servername}" --args ${execstring} &
     elif [[ "${LOGLEVEL,,}" == "error" ]]; then
-        { exec s6wrap --prepend="${APPNAME}][${params[0]}" --timestamps --args ${execstring} 2>&1 >/dev/null; } &
+        "${s6wrap[@]}" --ignore-stdout --prepend="${APPNAME}][${servername}" --args ${execstring} &
     elif [[ "${LOGLEVEL,,}" == "none" ]]; then
-       { exec ${execstring} >/dev/null 2>/dev/null; } &
+        "${s6wrap[@]}" --ignore-stderr --ignore-stdout --prepend="${APPNAME}][${servername}" --args ${execstring} &
     fi
 
     # pid_array is indexed by the PID of each mlat_client and contains the MLAT_PARAMs for that instance
@@ -212,7 +220,7 @@ do
     pid_array[$!]="${MLAT_PARAM[*]}"
 done
 
-sleep 5
+sleep 5 &; wait $!
 
 # All MLAT Clients are up, so set the flag. This flag is read by MLATHUB as a sign that it's
 # safe to start up
@@ -226,26 +234,26 @@ do
         if ! kill -0 "${mlat_pid}" >/dev/null 2>&1
         then
             # it exited - let's restart:
-            sleep "${RESTARTTIMER}"
+            sleep "${RESTARTTIMER}" &; wait $!
             servername="$(awk '{print $4}' <<< "${pid_array[$mlat_pid]}")"
             servername="${servername%%:*}"
 
-            [[ "${LOGLEVEL,,}" != "none" ]] && s6wrap --prepend="${APPNAME}[${servername}" --timestamps --args echo "MLAT_Client ${servername} exited. Attempting to restart." || true
+            [[ "${LOGLEVEL,,}" != "none" ]] && "${s6wrap[@]}" --prepend="${APPNAME}[${servername}" --args echo "MLAT_Client ${servername} exited. Attempting to restart." || true
             # shellcheck disable=SC2086
             execstring="$(echo ${MLAT_CMD} ${pid_array[$mlat_pid]} | xargs)"
 
             #shellcheck disable=SC2069,SC2086
             if [[ -z "${LOGLEVEL}" ]] || [[ "${LOGLEVEL,,}" == "verbose" ]]; then
-                { exec s6wrap --prepend="${APPNAME}][${servername}" --timestamps --args ${execstring} 2>&1; } &
+                "${s6wrap[@]}" --prepend="${APPNAME}][${servername}" --args ${execstring} &
             elif [[ "${LOGLEVEL,,}" == "error" ]]; then
-                { exec s6wrap --prepend="${APPNAME}][${servername}" --timestamps --args ${execstring} 2>&1 >/dev/null; } &
+                "${s6wrap[@]}" --ignore-stdout --prepend="${APPNAME}][${servername}" --args ${execstring} &
             elif [[ "${LOGLEVEL,,}" == "none" ]]; then
-                { exec ${execstring} >/dev/null 2>/dev/null; } &
+                "${s6wrap[@]}" --ignore-stderr --ignore-stdout --prepend="${APPNAME}][${servername}" --args ${execstring} &
             fi
 
             pid_array[$!]="${pid_array[${mlat_pid}]}"
             unset "pid_array[${mlat_pid}]"
         fi
     done
-    sleep 10
+    sleep 10 &; wait $!
 done
